## prepare input

In [20]:
text = "Medical  sciences  have  long  since  established an ethics code for experiments,  to minimize the risk of harm to subjects. Natural  language  processing  (NLP)  used  to involve  mostly  anonymous  corpora,  withthe  goal  of  enriching  linguistic  analysis, and  was  therefore  unlikely  to  raise  ethical  concerns.   As  NLP  becomes  increasingly  wide-spread  and  uses  more  datafrom social media, however, the situationhas changed: the outcome of NLP experiments and applicationscannow have a direct effect on individual users’ lives. Until now, the discourse on this topic in the field has not followed the technological development, while public discourse was often focused on exaggerated dangers.  This position paper tries to take back the initiative and start a discussion. We identify a number of social implications of NLP and discuss their ethical significance,  as well as ways to address them."

In [21]:
# sent tokenizer
import nltk
# nltk.download('punkt')
from nltk import tokenize

sent_list = tokenize.sent_tokenize(text)
sent_list

['Medical  sciences  have  long  since  established an ethics code for experiments,  to minimize the risk of harm to subjects.',
 'Natural  language  processing  (NLP)  used  to involve  mostly  anonymous  corpora,  withthe  goal  of  enriching  linguistic  analysis, and  was  therefore  unlikely  to  raise  ethical  concerns.',
 'As  NLP  becomes  increasingly  wide-spread  and  uses  more  datafrom social media, however, the situationhas changed: the outcome of NLP experiments and applicationscannow have a direct effect on individual users’ lives.',
 'Until now, the discourse on this topic in the field has not followed the technological development, while public discourse was often focused on exaggerated dangers.',
 'This position paper tries to take back the initiative and start a discussion.',
 'We identify a number of social implications of NLP and discuss their ethical significance,  as well as ways to address them.']

In [22]:
# remove punctuation
import string

sent_list = [s.translate(str.maketrans('', '', string.punctuation)) for s in sent_list]
sent_list

['Medical  sciences  have  long  since  established an ethics code for experiments  to minimize the risk of harm to subjects',
 'Natural  language  processing  NLP  used  to involve  mostly  anonymous  corpora  withthe  goal  of  enriching  linguistic  analysis and  was  therefore  unlikely  to  raise  ethical  concerns',
 'As  NLP  becomes  increasingly  widespread  and  uses  more  datafrom social media however the situationhas changed the outcome of NLP experiments and applicationscannow have a direct effect on individual users’ lives',
 'Until now the discourse on this topic in the field has not followed the technological development while public discourse was often focused on exaggerated dangers',
 'This position paper tries to take back the initiative and start a discussion',
 'We identify a number of social implications of NLP and discuss their ethical significance  as well as ways to address them']

In [23]:
# word tokenizer
from nltk.tokenize import word_tokenize

tokenized_sents = [word_tokenize(i) for i in sent_list]
tokenized_sents

[['Medical',
  'sciences',
  'have',
  'long',
  'since',
  'established',
  'an',
  'ethics',
  'code',
  'for',
  'experiments',
  'to',
  'minimize',
  'the',
  'risk',
  'of',
  'harm',
  'to',
  'subjects'],
 ['Natural',
  'language',
  'processing',
  'NLP',
  'used',
  'to',
  'involve',
  'mostly',
  'anonymous',
  'corpora',
  'withthe',
  'goal',
  'of',
  'enriching',
  'linguistic',
  'analysis',
  'and',
  'was',
  'therefore',
  'unlikely',
  'to',
  'raise',
  'ethical',
  'concerns'],
 ['As',
  'NLP',
  'becomes',
  'increasingly',
  'widespread',
  'and',
  'uses',
  'more',
  'datafrom',
  'social',
  'media',
  'however',
  'the',
  'situationhas',
  'changed',
  'the',
  'outcome',
  'of',
  'NLP',
  'experiments',
  'and',
  'applicationscannow',
  'have',
  'a',
  'direct',
  'effect',
  'on',
  'individual',
  'users',
  '’',
  'lives'],
 ['Until',
  'now',
  'the',
  'discourse',
  'on',
  'this',
  'topic',
  'in',
  'the',
  'field',
  'has',
  'not',
  'follo

In [24]:
# lower casing
tokenized_sents = [[t.lower() for t in s] for s in tokenized_sents]
tokenized_sents[0]

['medical',
 'sciences',
 'have',
 'long',
 'since',
 'established',
 'an',
 'ethics',
 'code',
 'for',
 'experiments',
 'to',
 'minimize',
 'the',
 'risk',
 'of',
 'harm',
 'to',
 'subjects']

### Genetic Alg

In [43]:
#defining various steps required for the genetic algorithm
import random

def initilization_of_population(pop_size,n_feat):
#     population = []
#     for i in range(size):
#         chromosome = np.ones(n_feat,dtype=np.bool)
#         chromosome[:int(0.3*n_feat)]=False
#         np.random.shuffle(chromosome)
#         population.append(chromosome)
#     return population
    return np.random.choice([0, 1], size=(pop_size, n_feat))

def fitness_score(population):
#     scores = []
#     for chromosome in population:
        
#     scores, population = np.array(scores), np.array(population) 
#     inds = np.argsort(scores)
#     return list(scores[inds][::-1]), list(population[inds,:][::-1])
    return [sum(p) for p in population], population

def selection(pop_after_fit,n_parents):
    population_nextgen = []
    for i in range(n_parents):
        population_nextgen.append(pop_after_fit[i])
    return population_nextgen

def crossover(pop_after_sel):
    population_nextgen=pop_after_sel
    for i in range(len(pop_after_sel)):
        child=pop_after_sel[i]
        child[3:7]=pop_after_sel[(i+1)%len(pop_after_sel)][3:7]
        population_nextgen.append(child)
    return population_nextgen

def mutation(pop_after_cross,mutation_rate):
    population_nextgen = []
    for i in range(0,len(pop_after_cross)):
        chromosome = pop_after_cross[i]
        for j in range(len(chromosome)):
            if random.random() < mutation_rate:
                chromosome[j]= not chromosome[j]
        population_nextgen.append(chromosome)
    #print(population_nextgen)
    return population_nextgen

def generations(size,n_feat,n_parents,mutation_rate,n_gen):
    best_chromo= []
    best_score= []
    population_nextgen=initilization_of_population(size,n_feat)
    for i in range(n_gen):
        scores, pop_after_fit = fitness_score(population_nextgen)
#         print(scores[:2])
        pop_after_sel = selection(pop_after_fit,n_parents)
        pop_after_cross = crossover(pop_after_sel)
        population_nextgen = mutation(pop_after_cross,mutation_rate)
        best_chromo.append(pop_after_fit[0])
        best_score.append(scores[0])
    return best_chromo,best_score

In [44]:
# sent
sent = tokenized_sents[0]

chromo,score=generations(size=20,n_feat=len(sent),n_parents=5,mutation_rate=0.10,n_gen=20)
chromo,score

([array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
         0, 1, 1, 1, 0, 1, 1, 1]),
  array([0